version: '3'

services:
  homeassistant:
    environment:
      - TZ=Europe/Rome
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - ./data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "8123:8123"
    network_mode: bridge

